@startuml [State]FSM_Player
[*] --> S_IDLE_JOUEUR

S_IDLE_JOUEUR : L'état où le joueur est inactif
S_RUNNING_JOUEUR : L'état où le joueur se déplace
S_INVENTORY_JOUEUR : L'état où le joueur est dans l'inventaire


S_IDLE_JOUEUR --> S_RUNNING_JOUEUR : I_MOVE
S_IDLE_JOUEUR --> S_INVENTORY_JOUEUR : I_INVENTORY
S_IDLE_JOUEUR --> S_IDLE_JOUEUR : I_ATTACK
S_IDLE_JOUEUR --> S_IDLE_JOUEUR : I_NONE

S_RUNNING_JOUEUR --> S_RUNNING_JOUEUR : I_MOVE
S_RUNNING_JOUEUR --> S_INVENTORY_JOUEUR : I_INVENTORY
S_RUNNING_JOUEUR --> S_RUNNING_JOUEUR : I_ATTACK
S_RUNNING_JOUEUR --> S_IDLE_JOUEUR : I_NONE

S_INVENTORY_JOUEUR --> S_INVENTORY_JOUEUR : I_MOVE
S_INVENTORY_JOUEUR --> S_IDLE_JOUEUR : I_INVENTORY
S_INVENTORY_JOUEUR --> S_INVENTORY_JOUEUR : I_ATTACK
S_INVENTORY_JOUEUR --> S_INVENTORY_JOUEUR : I_NONE

@enduml

@enduml